### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by rufimelo99** [UKPLab/sentence-transformers#1646]
Firstly, Thanks for your work! Really Impressive!

I was trying to use the training_nli_v2.py script to fine tune a BERT model on a server.

It did not work and returned a CUDA error.

![ola](https://user-images.githubusercontent.com/44201826/180262906-3eb935d9-d5b9-486b-a21e-be78532116e8.png)

Requirements Versions:
- transformers               4.20.1
- tokenizers                   0.12.1
- tqdm                           4.64.0
- torch                           1.12.0
- torchvision                  0.13.0
- numpy                        1.23.1
- scikit-learn                  1.1.1
- scipy                           1.8.1
- nltk                              3.7
- sentencepiece             0.1.96
- huggingface-hub        0.8.1

Am I missing any configuration?

**Comment by rufimelo99** [comment]
Solved by changing the packages version to match this:
``````
pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html ```

https://pytorch.org/get-started/previous-versions/
