### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by manzoorali29** [UKPLab/sentence-transformers#394]
While running the semantic search example I faced this issue. I tried to remove the line cos_scores = cos_scores.cpu() but still get the same issue. I tried with two different pre-trained models .the clustering is doing great but the semantic search have this issue.

**Comment by WangHexie** [comment]
I solved this error by restarting the console and using sklearn and scipy to calculate the distance other than the sample code.

**Comment by manzoorali29** [comment]
still facing the same issue using the sample code....

**Comment by nreimers** [comment]
Maybe this issue is helpful:
https://github.com/pytorch/pytorch/issues/21819

Appears to be a general issue with pytorch.

One solution could be to try to reduce the batch size.

**Comment by ajyl** [comment]
@manzoorali29  I was running into the same error seen in the sample script. However, per one of the comments seen in pytorch/pytorch#21819, it seems like the problem occurs when two tensors that are on different devices (cpu, gpu) are being multiplied, and then accessed later.

To fix this, in the function `pytorch_cos_sim()` in `util.py`, where it returns `torch.mm(a_norm, b_norm.transpose(0, 1))`, I added `.cpu()` to both `a_norm` and `b_norm` before returning. (Or alternatively adding `.cuda()` to each tensor)
