### ISSUE TITLE
CUDA error for long sentences?

### ISSUE THREAD

**Issue by freeIsa** [UKPLab/sentence-transformers#459]
Hello,
I am using Sentence Transformers, specifically `distiluse-base-multilingual-cased`, to compute semantic similarity for a list of sentences. I have been getting CUDA errors (last of which was ```CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)` ```) on a specific dataset, and after some investigation I realized this was due to a specific sentence of 2115 characters, which gets tokenized to 580 tokens. I am aware this is longer than the model `max_seq_length` (which I set to 512), but I was expecting the sentence to be automatically truncated to the maximum length with no error arising.
Am I doing something wrong? 
I am running version 0.3.2 (transformers version 3.0.2).

**Comment by PhilipMay** [comment]
This is how you can use the tokenizer to truncate. Just fyi:

```python
data_text_encodings = tokenizer(data_text, truncation=True, padding=True, max_length=max_seq_len)
```

**Comment by PhilipMay** [comment]
Also see this discussion about pre tokenization: https://github.com/UKPLab/sentence-transformers/issues/453

**Comment by nreimers** [comment]
Hi @freelsa,
yes, the sentences are truncated to the max length.

However, BERT as a quadratic memory requirement with sentence length. Hence, long sentences can easily blow up your GPU memory.

What you can do:
- Reduce the batch size. 
- Reduce the max sequence length until you no longer get an OOM
- Use a smaller model (like DistilBERT or even smaller).

**Comment by PhilipMay** [comment]
> What you can do:

Or add more GPUs. :-)

**Comment by nreimers** [comment]
> > What you can do:
> 
> Or add more GPUs. :-)

Or buy a GPU with more memory ;)

**Comment by PhilipMay** [comment]
Here is a nice Blog about multi GPU training BTW: https://medium.com/huggingface/training-larger-batches-practical-tips-on-1-gpu-multi-gpu-distributed-setups-ec88c3e51255

PS: Scroll down and do not get confused by the full screen image like I was...

**Comment by freeIsa** [comment]
Thanks everyone for your comments! I am not convinced it is actually a memory problem, as I get the same error when trying to process that single sentence alone. Just to be clear, this is the code I am running:
```
model = SentenceTransformer('distiluse-base-multilingual-cased')
model._first_module().max_seq_length = 512
text_embeddings = model.encode(texts, convert_to_tensor=True)
```
where `texts` is a list of one element (the "long" sentence mentioned above).
Actually, I just tried removing the second line (the one setting `max_seq_length`) and now everything works fine, so I guess that is not the correct way to change this parameter. Can you point me to the right command please?

**Comment by nreimers** [comment]
Try
```
model._first_module().max_seq_length = 509
```

Transformer models add up to 3 special tokens like [CLS] and/or [SEP] to your input sentence. So if your sentence is 512 tokens, and 3 special tokens are added, this would result in too many tokens passed to the transformers model.

**Comment by freeIsa** [comment]
Great, that made it! :) Thank you so much for you help!

**Comment by thesby** [comment]
@nreimers Hi, I meet a problem here. My model accept 2048 tokens, but if I try to encode a sentence much longer than 2048 tokens, `CUDA error` will occur. I find that the tokenizer doesn't truncate the sentence if I use `tokenizer.encode(text)`, though I have set  `model._first_module().max_seq_length = 2048`. But I find it truncates when I use `tokenizer.encode(text, max_length=2048)`. How to fix it when using `model.encode(text)`?

**Comment by thesby** [comment]
I fix it by modify the Transformer class
```
    def tokenize(self, text: Union[str, List[str]]) -> List[int]:
        """
        Tokenizes a text and maps tokens to token-ids
        """
        if isinstance(text, str):
            return self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize(text, max_length=self.max_seq_length-3))
        else:
            return [self.tokenizer.convert_tokens_to_ids(self.tokenizer.tokenize(t, max_length=self.max_seq_length-3)) for t in text]
```
