### ISSUE TITLE
Suddenly PyTorch isn't allocating anymore bytes

### ISSUE THREAD

**Issue by AhmedTawfek** [UKPLab/sentence-transformers#527]
The BERT SentenceTransformer was working normally up until 2 days ago and now suddenly causing this error while running the same code. Any idea what is the problem?

RuntimeError: CUDA out of memory. Tried to allocate 90.00 MiB (GPU 0; 14.76 GiB total capacity; 0 bytes already allocated; 43.44 MiB free; 0 bytes reserved in total by PyTorch)

**Comment by nreimers** [comment]
Looks like something is using too much CUDA memory. You can try to reduce the batch size or reduce the max sequence length of your samples.

**Comment by PhilipMay** [comment]
Is it happening while training or creating embeddings?
Maybe it is related to #522 and #487
See my PR here #525

**Comment by AhmedTawfek** [comment]
@nreimers I tried clearing the cache and restarting the machines a couple of times but I will try to do so again. The fact that PyTorch is only allocating 0 bytes is what doesn't really make sense.

@PhilipMay I'm only creating embeddings by passing a very few amount of documents so there is no large batch or sequence length that is causing the problem. 

As I said, it was working normally on the same dataset a couple days ago so it may be related to what @nreimers is suggesting about having another process blocking CUDA memory or some old dead process has still CUDA memory allocated.

Thank you anyways, if you have anything else to share with me please do.

**Comment by nreimers** [comment]
You can check this by running nvidia-smi or gpustat:
https://github.com/wookayin/gpustat

**Comment by AhmedTawfek** [comment]
I just figured out what is the problem:
After I ran gpustat I found that there is 0% free RAM.
The reason is that every time, I load the Universal Sentence Encoder from TensorFlow and it takes 100% of memory once loaded. I now stopped loading the other model unless I needed it.
Thank you very much for you support, it's now working again. 💯

**Comment by nreimers** [comment]
Yes, tensorflow grabs all the GPU when you start it.

You can configure TF so that it just allocates the GPU memory that it actually needs.
