### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by thesby** [UKPLab/sentence-transformers#596]
When I training a model, the error happens. But there is no error if the model run inference. It seems an error happens when evaluating on dev dataset before the first step of training
sentence-transformers: 0.3.9
```
2020-11-30 20:25:50 - TripletEvaluator: Evaluating the model on dev dataset:
/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Traceback (most recent call last):
  File "train_triplet.py", line 188, in <module>
    train(train_set, dev_triplets, test_triplets, margin)
  File "train_triplet.py", line 165, in train
    dev_evaluator(model)
  File "../sentence_embedding/my_triplet_evaluator.py", line 70, in __call__
    show_progress_bar=self.show_progress_bar, convert_to_numpy=True)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 180, in encode
    out_features = self.forward(features)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/sentence_transformers/models/Transformer.py", line 36, in forward
    output_states = self.auto_model(**features)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 694, in forward
    return_dict=return_dict,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 418, in forward
    encoder_attention_mask,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 163, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 74, in forward
    outputs = run_function(*args)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 408, in custom_forward
    return module(*inputs, output_attentions)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 345, in forward
    output_attentions=output_attentions,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 279, in forward
    output_attentions,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 213, in forward
    context_layer = torch.matmul(attention_probs, value_layer)
RuntimeError: CUDA error: device-side assert triggered
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.118.02   Driver Version: 440.118.02   CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:B2:00.0 Off |                    0 |
| N/A   34C    P0    52W / 300W |     12MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:DB:00.0 Off |                    0 |
| N/A   33C    P0    38W / 300W |     12MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by thesby** [comment]
sometimes another error occurs
```
2020-11-30 20:56:03 - TripletEvaluator: Evaluating the model on dev dataset:
/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Traceback (most recent call last):
  File "train_triplet.py", line 189, in <module>
    train(train_set, dev_triplets, test_triplets, margin)
  File "train_triplet.py", line 166, in train
    dev_evaluator(model)
  File "../sentence_embedding/my_triplet_evaluator.py", line 70, in __call__
    show_progress_bar=self.show_progress_bar, convert_to_numpy=True)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py", line 180, in encode
    out_features = self.forward(features)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/sentence_transformers/models/Transformer.py", line 36, in forward
    output_states = self.auto_model(**features)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 694, in forward
    return_dict=return_dict,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 418, in forward
    encoder_attention_mask,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 163, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 74, in forward
    outputs = run_function(*args)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 408, in custom_forward
    return module(*inputs, output_attentions)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 345, in forward
    output_attentions=output_attentions,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 279, in forward
    output_attentions,
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/transformers/modeling_roberta.py", line 178, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/admin/work_dir/.local/lib/python3.7/site-packages/torch/nn/functional.py", line 1676, in linear
    output = input.matmul(weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by nreimers** [comment]
Have a look here:
https://towardsdatascience.com/cuda-error-device-side-assert-triggered-c6ae1c8fa4c3

it appears that the triples you pass / use with TripletEvaluator appear to use invalid data

**Comment by thesby** [comment]
I skipped the evaluation, but got another error: cuda out of memory.
Since I use the longformer model, I need to replace the attention layers with its special attention method. But how to initialize a sentence transformer model from an initialized (preprocessed) transformer model ? I find that `models.Transformer` cannot accept a model.

**Comment by nreimers** [comment]
@thesby 
If Longformer works with huggingface AutoModel, then you can create you model like this:
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

**Comment by thesby** [comment]
I solved it. Using the latest transformers api of `Longformer` will be OK, not the example of longformer repo.
