### ISSUE TITLE
LaBSE CUDA Out of Memory on 16 GB GPU

### ISSUE THREAD

**Issue by ejshieh** [UKPLab/sentence-transformers#896]
First off, thank you for creating this wonderful package!

I am trying to fine-tune LaBSE on a small corpus and am running out of memory on even the first training example of the first iteration when using CUDA (on 16 GB Tesla V100 GPUs). The code I am running works fine on CPU.

```
RuntimeError: CUDA out of memory. Tried to allocate 1.44 GiB (GPU 0; 15.78 GiB total capacity; 10.88 GiB already allocated; 318.00 MiB free; 14.16 GiB reserved in total by PyTorch)
```

I looked through similar issues in this repo and have already tried the following:

* Reducing batch size (I dropped it down to 1, and it still fails)
* Setting max_seq_len (I reduced this down to 10 and also verified that the training InputExample consists of short text fragments, <5 tokens each)

Interestingly enough, regardless of these changes Torch is consistently trying to allocate 1.44 GB in the first training iteration. Any ideas why this might be happening? Your help is appreciated!

More details:
* I am running my code on SageMaker `ml.p3.8xlarge` instances
* I am using the pre-trained LaBSE model downloaded directly from https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/LaBSE.zip (I had some issues downloading from the default URL in SageMaker, it seems like sbert.net was blocking traffic?)
* My code works just fine when I use CPU

Thank you!

**Comment by nreimers** [comment]
Not sure why it happens.

In colab, also with a 16GB GPU, it runs fine with batch size 16 and no limit to the sequence length:
https://colab.research.google.com/drive/167prHLgEWT7gy63KJMNiDUtnn68QJldH?usp=sharing

Are you sure the GPU is empty before you start the training process? Is another process maybe blocking GPU memory? You can check this by executing nvidia-smi

**Comment by ejshieh** [comment]
Thanks for the rapid response @nreimers as well as for providing this helpful tutorial.

It turns out the GPU memory was not being freed up before starting the training. Killing the old process and setting the max_seq_len to 20 seems to work quite well. Thanks again!
